#!/bin/bash

# tmux wrapper
# 	tm session-name [window-name]
# Names can be partial from the beginning and first match will connect.
# If no match is found a new session will be created.
# If there's a second argument, it will be used to attach directly to a
# window in the session, or to name the first window in a new session.
tm() {
	local tmux_cmd
	tmux_cmd=${TM_TMUX_COMMAND:-"tmux"}
	local attach window should_detach

	if [ -n "$1" ]; then
		attach=""
		should_detach=""

		if [[ $1 =~ -?d(etach)?$ && $# > 1 ]]; then
			should_detach="-d "
			shift
		fi

		tmux has-session -t $1 > /dev/null
		if [ $? -eq 0 ]; then
			attach=$1
			shift
		else
			for session in `tmux ls|awk -F ":" '{ print $1 }'`;do
				if [[ $session =~ ^$1  ]]; then
					echo "Matched session: $session"
					attach=$session
					shift
					break
				fi
			done
		fi

		if [[ $attach != "" ]]; then
			if [ $# -eq 1 ]; then
				for win in `tmux list-windows -t $attach|sed -E 's/^[0-9]+: //'|sed -E 's/[*-].*//'`;do
					if [[ $win =~ ^$1 ]]; then
						echo "Matched window: $window"
						window=$win
						break
					fi
				done

				$tmux_cmd attach ${should_detach}-t $attach:$window
			else
				$tmux_cmd attach ${should_detach}-t $attach
			fi
		else
			if [ $# -gt 1 ]; then
				attach=$1
				shift
				$tmux_cmd new -s $attach -n $1
			else
				echo "Attempting to create $1"
				$tmux_cmd new -s $1
			fi
		fi
	else
		$tmux_cmd ls
	fi
}

tm $@
