complete -xc howzit -a "(howzit -L)"
complete -c howzit -l default  -d "Answer all prompts with default response"
complete -c howzit -x -s m -l matching -a "partial exact fuzzy beginswith" -d "Topics matching type"
complete -c howzit -x -l multiple -a "first best all choose" -d "Multiple result handling"
complete -c howzit -s u -l no-upstream -d "Don't traverse up parent directories for additional build notes"
complete -c howzit -s u -l upstream -d "Traverse up parent directories for additional build notes"
complete -c howzit -s L -l list-completions -d "List topics for completion"
complete -c howzit -s l -l list -d "List available topics"
complete -c howzit -s R -l list-runnable -d "List topics containing @ directives (verbose)"
complete -c howzit -s T -l task-list -d "List topics containing @ directives (completion-compatible)"
complete -c howzit -l templates -d "List available templates"
complete -c howzit -l title-only -d "Output title only"
complete -c howzit -s c -l create -d "Create a skeleton build note in the current working directory"
complete -c howzit -f -l config-get -d "Display the configuration settings or setting for a specific key"
complete -c howzit -f -l config-set -d "Set a config value (must be a valid key)"
complete -c howzit -l edit-config -d "Edit configuration file using editor (subl)"
complete -c howzit -s e -l edit -d "Edit buildnotes file in current working directory using editor (subl)"
complete -c howzit -x -l grep -d "Display sections matching a search pattern"
complete -c howzit -s r -l run -a "(howzit -T)" -d "Execute @run, @open, and/or @copy commands for given topic"
complete -c howzit -s s -l select -d "Select topic from menu"
complete -c howzit -l color -d "Colorize output (default on)"
complete -c howzit -l no-color -d "Don't colorize output (default on)"
complete -c howzit -x -l header-format -d "Formatting style for topic titles (border, block)"
complete -c howzit -l md-highlight -d "Highlight Markdown syntax (default on), requires mdless or mdcat"
complete -c howzit -l no-md-highlight -d "Don't highlight Markdown syntax (default on), requires mdless or mdcat"
complete -c howzit -l pager -d "Paginate output (default on)"
complete -c howzit -l no-pager -d "Don't paginate output (default on)"
complete -c howzit -l show-code -d "Display the content of fenced run blocks"
complete -c howzit -s t -l title -d "Output title with build notes"
complete -c howzit -x -s w -l wrap  -d "Wrap to specified width (default 80, 0 to disable)"
complete -c howzit -s d -l debug -d "Show debug messages (and all messages)"
complete -c howzit -s q -l quiet -d "Silence info message"
complete -c howzit -l verbose -d "Show all messages"
complete -c howzit -s h -l help -d "Display this screen"
complete -c howzit -s v -l version -d "Display version number"
