complete -c license -f -n "__fish_use_subcommand" -a mit
complete -c license -f -n "__fish_use_subcommand" -a gpl-3.0
complete -c license -f -n "__fish_use_subcommand" -a gpl-2.0
complete -c license -f -n "__fish_use_subcommand" -a agpl-3.0
complete -c license -f -n "__fish_use_subcommand" -a unlicense
complete -c license -f -n "__fish_use_subcommand" -a apache-2.0
complete -c license -f -n "__fish_use_subcommand" -a epl-1.0
complete -c license -f -n "__fish_use_subcommand" -a bsd-2-clause
complete -c license -f -n "__fish_use_subcommand" -a mpl-2.0
complete -c license -f -n "__fish_use_subcommand" -a bsd-3-clause
complete -c license -f -n "__fish_use_subcommand" -a lgpl-3.0
complete -c license -f -n "__fish_use_subcommand" -a lgpl-2.1
complete -c license -f -n "__fish_use_subcommand" -a wtfpl
